name: CI
on: [push]
jobs:
  standard-checks:
    name: Lint & Test
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17.3.0"
      
      - name: Install packages
        run: npm ci
      - name: Run eslint
        run: npm run ci:lint
      - name: Run Tests
        run: npm run ci:test
      - name: Bundle and Output
        run: npm run build
        
